format_version: 10
pipelines:
  testing-building:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-d87dea5:
        git: https://github.com/Afk-Akash/micronaut-test-project
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Test:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            run-test:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - test
                    command: ./mvnw
                    run_if: passed
                - exec:
                    arguments:
                      - clean
                      - package
                    command: ./mvnw
                    run_if: passed
          artifacts:
            - source:
                - '**/target/*.jar'
              destination: 'all-artifacts'  
